blueprint:
  name: "AWTRIX Overview App 🌡️💧🔋"
  description:
    "Visualizza temperatura, umidità e batteria in un'unica schermata sul tuo AWTRIX.\n\n
    ## ⚠️ REQUISITI ⚠️\n
    - Dispositivo AWTRIX 3\n
    - Integrazione MQTT configurata\n
    - Sensori di temperatura, umidità e batteria in Home Assistant\n\n
    ## 📊 LAYOUT\n
    Layout su singola schermata:\n
    - Temperatura e Umidità come testo\n
    - Barra di progresso batteria (sopra o sotto)\n\n
    ## 📦 ICONE OPZIONALI\n
    Puoi aggiungere piccole icone:\n
    - `thermometer` - Termometro\n
    - `water` - Goccia d'acqua\n\n
    Aggiornamenti: https://github.com/Raythekool/ha-awtrix-overview-app"
  domain: automation
  input:
    awtrix:
      name: Dispositivo AWTRIX
      description: Seleziona il tuo dispositivo AWTRIX
      selector:
        device:
          integration: mqtt
          manufacturer: Blueforcer
          model: AWTRIX 3
          multiple: true

    temperature_sensor:
      name: Sensore Temperatura 🌡️
      description: Sensore di temperatura da visualizzare
      selector:
        entity:
          filter:
            - domain: sensor
              device_class: temperature

    humidity_sensor:
      name: Sensore Umidità 💧
      description: Sensore di umidità da visualizzare
      selector:
        entity:
          filter:
            - domain: sensor
              device_class: humidity

    battery_sensor:
      name: Sensore Batteria 🔋
      description: Sensore di livello batteria da visualizzare
      selector:
        entity:
          filter:
            - domain: sensor
              device_class: battery

    show_icon:
      name: Mostra Icona 🎨
      description: Mostra un'icona a sinistra del testo
      selector:
        boolean: {}
      default: false

    icon_name:
      name: Nome Icona
      description: "Nome dell'icona da mostrare (se abilitata sopra).\nEsempio: thermometer, home, weather"
      selector:
        text: {}
      default: "home"

    temp_unit:
      name: Unità Temperatura
      description: "Unità di misura da mostrare"
      selector:
        select:
          options:
            - label: "°C (Celsius)"
              value: "°C"
            - label: "°F (Fahrenheit)"
              value: "°F"
            - label: "° (solo simbolo)"
              value: "°"
      default: "°C"

    bar_position:
      name: Posizione Barra Batteria
      description: "Dove mostrare la barra di progresso della batteria"
      selector:
        select:
          options:
            - label: "In alto (top bar)"
              value: "top"
            - label: "In basso (bottom bar)"
              value: "bottom"
      default: "bottom"

    text_color:
      name: Colore Testo
      description: "Colore del testo (se vuoi colore fisso invece di dinamico)"
      selector:
        select:
          options:
            - label: "Dinamico (cambia in base ai valori)"
              value: "dynamic"
            - label: "Bianco"
              value: "#FFFFFF"
            - label: "Verde"
              value: "#00FF00"
            - label: "Blu"
              value: "#0080FF"
            - label: "Giallo"
              value: "#FFFF00"
            - label: "Arancione"
              value: "#FFA500"
      default: "dynamic"

    refresh_interval:
      name: Intervallo Aggiornamento ⏱️
      description: Aggiorna i dati ogni X minuti (oltre agli aggiornamenti automatici)
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: min
          step: 1
          mode: slider
      default: 5

mode: restart

variables:
  device_ids: !input awtrix
  app_topic: "overview"
  devices_topics: |
    {%- macro get_device_topic(device_id) %}
      {{ states((device_entities(device_id) | select('search','device_topic') | list)[0]) }}
    {%- endmacro %}
    {%- set ns = namespace(devices=[]) %}
    {%- for device_id in device_ids %}
      {%- set device=get_device_topic(device_id)|replace('','') %}
      {% set ns.devices = ns.devices + [ device ~ '/custom/' ~ app_topic] %}
    {%- endfor %}
    {{ ns.devices | reject('match','unavailable') | list }}

  temperature_sensor: !input temperature_sensor
  humidity_sensor: !input humidity_sensor
  battery_sensor: !input battery_sensor
  show_icon: !input show_icon
  icon_name: !input icon_name
  temp_unit: !input temp_unit
  bar_position: !input bar_position
  text_color: !input text_color

  # Get sensor values
  temperature: "{{ states(temperature_sensor) | float(0) | round(1) }}"
  humidity: "{{ states(humidity_sensor) | float(0) | round(0) }}"
  battery: "{{ states(battery_sensor) | float(0) | round(0) }}"

  # Dynamic text color based on temperature (if dynamic selected)
  display_color: |
    {%- if text_color == 'dynamic' %}
      {%- set temp = states(temperature_sensor) | float(0) %}
      {%- if temp < 15 %}
        "#0080FF"
      {%- elif temp < 20 %}
        "#00FF00"
      {%- elif temp < 25 %}
        "#90FF00"
      {%- elif temp < 30 %}
        "#FFA500"
      {%- else %}
        "#FF0000"
      {%- endif %}
    {%- else %}
      "{{ text_color }}"
    {%- endif %}

  # Battery progress bar color
  battery_color: |
    {%- set batt = states(battery_sensor) | float(0) %}
    {%- if batt > 60 %}
      "#00FF00"
    {%- elif batt > 30 %}
      "#FFFF00"
    {%- else %}
      "#FF0000"
    {%- endif %}

  # Build text: "22.5° 45%" or with icon
  display_text: "{{ temperature }}{{ temp_unit }} {{ humidity }}%"

  # Main payload
  payload: |
    {
      {%- if show_icon %}
      "icon": "{{ icon_name }}",
      {%- endif %}
      "text": "{{ display_text }}",
      "color": {{ display_color }},
      {%- if bar_position == 'top' %}
      "topbar": {
        "value": {{ battery }},
        "color": {{ battery_color }},
        "backgroundColor": "#222222"
      }
      {%- else %}
      "progress": {{ battery }},
      "progressC": {{ battery_color }},
      "progressBC": "#222222"
      {%- endif %}
      {%- if states(battery_sensor) | float(0) < 20 %},
      "effect": "Fade"
      {%- endif %}
    }

trigger:
  - platform: state
    entity_id: !input temperature_sensor
    id: temp_change
  - platform: state
    entity_id: !input humidity_sensor
    id: humidity_change
  - platform: state
    entity_id: !input battery_sensor
    id: battery_change
  - platform: time_pattern
    minutes: "/{{ refresh_interval }}"
    id: refresh

condition:
  - condition: template
    value_template: "{{ has_value(temperature_sensor) and has_value(humidity_sensor) and has_value(battery_sensor) }}"

action:
  - repeat:
      for_each: "{{ devices_topics }}"
      sequence:
        - service: mqtt.publish
          data:
            qos: 0
            retain: false
            topic: "{{ repeat.item }}"
            payload: "{{ payload }}"
